version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: python run.py
      - run: date
      
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "00 19 * * *"
          filters:
            branches:
              only: 
                - develop
    jobs:
      - build
